apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-deployment
    name: app-mealie
  name: mealie-deployment
  namespace: app-mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-deployment
  template:
    metadata:
      labels:
        app: mealie-deployment
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:nightly
        name: mealie
        ports:
          - containerPort: 9000
